name: manage-azure-policy-6dbd35df
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'Audit tags/policies/Audit_tags_for_subs_&_RGs_0a69d343-c158-45f2-af62-7f0bdb8a630b/**'
#      - .github/workflows/manage-azure-policy-6dbd35df.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_6dbd35df}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          Audit tags/policies/Audit_tags_for_subs_&_RGs_0a69d343-c158-45f2-af62-7f0bdb8a630b/**
